// GENERATED by scripts/build-perfume-render.cjs from parfumdeclaration-web — do not edit
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// lib/perfume-render/entry.ts
var entry_exports = {};
__export(entry_exports, {
  renderPerfumeCard: () => renderPerfumeCard
});
module.exports = __toCommonJS(entry_exports);
var import_sharp5 = __toESM(require("sharp"));

// ../parfumdeclaration-web/apps/api/src/lib/premium-bg.ts
var import_sharp2 = __toESM(require("sharp"));

// ../parfumdeclaration-web/apps/api/src/lib/upscale.ts
var import_node_path = __toESM(require("node:path"));
var import_sharp = __toESM(require("sharp"));
var ort = __toESM(require("onnxruntime-node"));
var MODEL = import_node_path.default.resolve(__dirname, "./models/real_esrgan_general_x4v3.onnx");
var TILE = 128;
var OVERLAP = 12;
var SCALE = 4;
var AI_MIX = 0.6;
var session = null;
function model() {
  session ??= ort.InferenceSession.create(MODEL, process.env.ORT_EP ? { executionProviders: [process.env.ORT_EP] } : { intraOpNumThreads: 2, interOpNumThreads: 1 });
  return session;
}
function starts(size) {
  if (size <= TILE) return [0];
  const out = [];
  for (let p = 0; p + TILE < size; p += TILE - 2 * OVERLAP) out.push(p);
  out.push(size - TILE);
  return [...new Set(out)];
}
async function esrgan(rgb, w, h) {
  const s = await model();
  const W3 = w * SCALE, H3 = h * SCALE;
  const out = Buffer.alloc(W3 * H3 * 3);
  const tile = new Float32Array(3 * TILE * TILE);
  for (const y of starts(h)) for (const x of starts(w)) {
    for (let ty = 0; ty < TILE; ty++) for (let tx = 0; tx < TILE; tx++) {
      const sy = Math.min(h - 1, y + ty), sx = Math.min(w - 1, x + tx);
      const i = (sy * w + sx) * 3;
      for (let c = 0; c < 3; c++) tile[c * TILE * TILE + ty * TILE + tx] = rgb[i + c] / 255;
    }
    const res = await s.run({ image: new ort.Tensor("float32", tile, [1, 3, TILE, TILE]) });
    const up = res.upscaled_image.data;
    const T = TILE * SCALE;
    const t0 = y === 0 ? 0 : OVERLAP, l0 = x === 0 ? 0 : OVERLAP;
    const t1 = y + TILE >= h ? Math.min(TILE, h - y) : TILE - OVERLAP;
    const l1 = x + TILE >= w ? Math.min(TILE, w - x) : TILE - OVERLAP;
    for (let oy = t0 * SCALE; oy < t1 * SCALE; oy++) for (let ox = l0 * SCALE; ox < l1 * SCALE; ox++) {
      const di = ((y * SCALE + oy) * W3 + x * SCALE + ox) * 3;
      for (let c = 0; c < 3; c++) {
        const v = up[c * T * T + oy * T + ox];
        out[di + c] = v <= 0 ? 0 : v >= 1 ? 255 : Math.round(v * 255);
      }
    }
  }
  return out;
}
async function aiUpscale(rgb, w, h) {
  const W3 = w * SCALE, H3 = h * SCALE;
  const [ai, plain] = await Promise.all([
    esrgan(rgb, w, h),
    (0, import_sharp.default)(rgb, { raw: { width: w, height: h, channels: 3 } }).resize(W3, H3, { kernel: "lanczos3" }).raw().toBuffer()
  ]);
  for (let i = 0; i < ai.length; i++) ai[i] = Math.round(ai[i] * AI_MIX + plain[i] * (1 - AI_MIX));
  return { data: ai, width: W3, height: H3 };
}
var SMALL_PHOTO = 900;
async function enhanceSmallPhoto(input) {
  const meta = await (0, import_sharp.default)(input, { failOn: "none" }).metadata();
  if (!meta.width || !meta.height || Math.max(meta.width, meta.height) >= SMALL_PHOTO) return null;
  const { data, info } = await (0, import_sharp.default)(input, { failOn: "none" }).rotate().removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const up = await aiUpscale(data, info.width, info.height);
  const k = 1600 / Math.max(up.width, up.height);
  return (0, import_sharp.default)(up.data, { raw: { width: up.width, height: up.height, channels: 3 } }).resize(Math.round(up.width * k), Math.round(up.height * k), { kernel: "lanczos3" }).jpeg({ quality: 90, mozjpeg: true }).toBuffer();
}

// ../parfumdeclaration-web/apps/api/src/lib/premium-bg.ts
var STYLE = {
  width: 1200,
  height: 1600,
  /** Product height as a share of the frame, and the widest it may get */
  productHeight: 0.6,
  productMaxWidth: 0.74,
  /** Where the product stands (share of the frame height) */
  floor: 0.8,
  /** Backdrop brightness: centre and how much darker the edges / floor get */
  bgCenter: 248,
  bgEdgeDrop: 22,
  bgFloorDrop: 6,
  shadow: 0.18,
  shadowCore: 0.22,
  reflection: 0.16,
  reflectionLength: 0.18,
  jpegQuality: 90
};
var backdropCache = /* @__PURE__ */ new Map();
function backdrop(W3 = STYLE.width, H3 = STYLE.height) {
  const cached = backdropCache.get(`${W3}x${H3}`);
  if (cached) return cached;
  const { bgCenter, bgEdgeDrop, bgFloorDrop } = STYLE;
  const buf = Buffer.alloc(W3 * H3 * 3);
  for (let y = 0; y < H3; y++) {
    const floor = Math.min(1, Math.max(0, (y - H3 * 0.7) / (H3 * 0.3)));
    for (let x = 0; x < W3; x++) {
      const r = Math.min(1.4, Math.hypot((x - W3 / 2) / (W3 * 0.75), (y - H3 * 0.36) / (H3 * 0.7)));
      const v = bgCenter - bgEdgeDrop * r ** 1.6 - bgFloorDrop * floor;
      const i = (y * W3 + x) * 3;
      buf[i] = v;
      buf[i + 1] = v;
      buf[i + 2] = v - 1.2;
    }
  }
  backdropCache.set(`${W3}x${H3}`, buf);
  return buf;
}
function isPremiumResult(data, w, h, channels) {
  if (Math.abs(w / h - STYLE.width / STYLE.height) > 0.01) return false;
  const bd = backdrop();
  const { width: W3, height: H3 } = STYLE;
  const spots = [[0.03, 0.03], [0.97, 0.03], [0.5, 0.03], [0.03, 0.5], [0.97, 0.5], [0.03, 0.97], [0.97, 0.97]];
  return spots.every(([fx, fy]) => {
    let a = 0, b = 0, n = 0;
    for (let dy = -3; dy <= 3; dy++) for (let dx = -3; dx <= 3; dx++) {
      const x = Math.round(fx * (w - 1)) + dx, y = Math.round(fy * (h - 1)) + dy;
      const X = Math.round(fx * (W3 - 1)) + dx, Y = Math.round(fy * (H3 - 1)) + dy;
      if (x < 0 || y < 0 || x >= w || y >= h || X < 0 || Y < 0 || X >= W3 || Y >= H3) continue;
      a += data[(y * w + x) * channels + 1];
      b += bd[(Y * W3 + X) * 3 + 1];
      n++;
    }
    return n > 0 && Math.abs(a / n - b / n) <= 4;
  });
}
function isWhiteBackground(data, w, h, channels) {
  const k = Math.max(4, Math.floor(w / 40));
  const stats = [0, 1, 2].map(() => ({ sum: 0, sq: 0, n: 0 }));
  const add = (x, y) => {
    const i = (y * w + x) * channels;
    for (let c = 0; c < 3; c++) {
      const v = data[i + c];
      stats[c].sum += v;
      stats[c].sq += v * v;
      stats[c].n++;
    }
  };
  for (let y = 0; y < h; y += 2) for (let x = 0; x < w; x += 2) {
    if (y < k || y >= h - k || x < k || x >= w - k) add(x, y);
  }
  return stats.every((s) => {
    const mean = s.sum / s.n;
    const sd = Math.sqrt(Math.max(0, s.sq / s.n - mean * mean));
    return mean > 243 && sd < 6;
  });
}
function flattenBackground(data, w, h, channels) {
  const k = Math.max(4, Math.floor(Math.min(w, h) / 40));
  const r = Math.max(3, Math.floor(Math.min(w, h) / 30));
  const out = Buffer.alloc(w * h * 3);
  const surfaces = [];
  const means = [];
  for (let c = 0; c < 3; c++) {
    const px = (x, y) => data[(y * w + x) * channels + c];
    const band = (n2, at) => Float32Array.from({ length: n2 }, (_, i) => {
      let s = 0;
      for (let j = 0; j < k; j++) s += at(i, j);
      return s / k;
    });
    const raw = [
      band(w, (x, j) => px(x, j)),
      band(w, (x, j) => px(x, h - 1 - j)),
      band(h, (y, j) => px(j, y)),
      band(h, (y, j) => px(w - 1 - j, y))
    ];
    const smooth = raw.map((a) => Float32Array.from(a, (_, i) => {
      let s = 0, n2 = 0;
      for (let j = Math.max(0, i - r); j <= Math.min(a.length - 1, i + r); j++) {
        s += a[j];
        n2++;
      }
      return s / n2;
    }));
    let sq = 0, n = 0, sum = 0, min = 255;
    raw.forEach((a, s) => a.forEach((v, i) => {
      const d = v - smooth[s][i];
      sq += d * d;
      sum += v;
      n++;
      min = Math.min(min, smooth[s][i]);
    }));
    if (Math.sqrt(sq / n) > 4 || min < 185) return null;
    means.push(sum / n);
    const [T, B, L, R] = smooth;
    const c00 = (T[0] + L[0]) / 2, c10 = (T[w - 1] + R[0]) / 2, c01 = (B[0] + L[h - 1]) / 2, c11 = (B[w - 1] + R[h - 1]) / 2;
    const S = new Float32Array(w * h);
    for (let y = 0; y < h; y++) {
      const v = y / (h - 1);
      for (let x = 0; x < w; x++) {
        const u = x / (w - 1);
        S[y * w + x] = (1 - v) * T[x] + v * B[x] + (1 - u) * L[y] + u * R[y] - ((1 - u) * (1 - v) * c00 + u * (1 - v) * c10 + (1 - u) * v * c01 + u * v * c11);
      }
    }
    surfaces.push(S);
  }
  if (Math.max(...means) - Math.min(...means) > 30) return null;
  for (let i = 0; i < w * h; i++) for (let c = 0; c < 3; c++) {
    const v = data[i * channels + c] * 255 / Math.max(1, surfaces[c][i]);
    out[i * 3 + c] = v >= 255 ? 255 : v;
  }
  return out;
}
function productBox(data, w, h, channels) {
  let x0 = w, y0 = h, x1 = -1, y1 = -1;
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const i = (y * w + x) * channels;
    if (255 - Math.min(data[i], data[i + 1], data[i + 2]) > 14) {
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  return x1 < 0 ? null : { left: x0, top: y0, width: x1 - x0 + 1, height: y1 - y0 + 1 };
}
function ellipse(x, y, cx, cy, rx, ry) {
  const d = ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2;
  return Math.exp(-d * 2.2);
}
async function premiumBackground(input, output = {}) {
  const src = (0, import_sharp2.default)(input, { failOn: "none" }).rotate().removeAlpha();
  const decoded = await src.clone().raw().toBuffer({ resolveWithObject: true });
  const { info } = decoded;
  let data = decoded.data;
  let channels = info.channels;
  let flattened = false;
  if (isPremiumResult(data, info.width, info.height, channels)) return null;
  if (!isWhiteBackground(data, info.width, info.height, channels)) {
    const flat = flattenBackground(data, info.width, info.height, channels);
    if (!flat || !isWhiteBackground(flat, info.width, info.height, 3)) return null;
    data = flat;
    channels = 3;
    flattened = true;
  }
  const box = productBox(data, info.width, info.height, channels);
  if (!box || box.width < 20 || box.height < 20) return null;
  if (flattened && (box.left < 2 || box.top < 2 || box.left + box.width > info.width - 2 || box.top + box.height > info.height - 2)) return null;
  const W3 = output.width || STYLE.width;
  const H3 = output.height || STYLE.height;
  const k = H3 / STYLE.height;
  let ch = Math.round(H3 * STYLE.productHeight);
  let cw = Math.round(box.width * ch / box.height);
  if (cw > W3 * STYLE.productMaxWidth) {
    cw = Math.round(W3 * STYLE.productMaxWidth);
    ch = Math.round(box.height * cw / box.width);
  }
  const crop = await (0, import_sharp2.default)(data, { raw: { width: info.width, height: info.height, channels } }).extract(box).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  let cropImg = (0, import_sharp2.default)(crop.data, { raw: { width: crop.info.width, height: crop.info.height, channels: 3 } });
  if (ch / box.height > 1.3 && box.width * box.height <= 1e6) {
    const up = await aiUpscale(crop.data, crop.info.width, crop.info.height);
    cropImg = (0, import_sharp2.default)(up.data, { raw: { width: up.width, height: up.height, channels: 3 } });
  }
  const product = await cropImg.resize(cw, ch, { kernel: "lanczos3" }).sharpen({ sigma: 0.8, m1: 0.6, m2: 1.4 }).raw().toBuffer();
  const out = Buffer.from(backdrop(W3, H3));
  const px = Math.round((W3 - cw) / 2);
  const base = Math.round(H3 * STYLE.floor);
  const py = base - ch;
  const y0 = Math.max(0, base - Math.round(60 * k)), y1 = Math.min(H3, base + Math.round(70 * k));
  for (let y = y0; y < y1; y++) for (let x = Math.max(0, px - Math.round(40 * k)); x < Math.min(W3, px + cw + Math.round(40 * k)); x++) {
    const soft = ellipse(x, y, px + cw / 2, base + 4 * k, cw * 0.46, 26 * k);
    const core = ellipse(x, y, px + cw / 2, base, cw * 0.32, 8 * k);
    const f = (1 - STYLE.shadow * soft) * (1 - STYLE.shadowCore * core);
    const i = (y * W3 + x) * 3;
    out[i] *= f;
    out[i + 1] *= f;
    out[i + 2] *= f;
  }
  const rl = Math.min(Math.round(ch * STYLE.reflectionLength), H3 - base);
  for (let r = 0; r < rl; r++) {
    const a = STYLE.reflection * (1 - r / rl);
    const sy = ch - 1 - r;
    for (let x = 0; x < cw; x++) {
      const si = (sy * cw + x) * 3, oi = ((base + r) * W3 + px + x) * 3;
      for (let c = 0; c < 3; c++) out[oi + c] *= 1 - a * (1 - product[si + c] / 255);
    }
  }
  for (let y = 0; y < ch; y++) for (let x = 0; x < cw; x++) {
    const si = (y * cw + x) * 3, oi = ((py + y) * W3 + px + x) * 3;
    for (let c = 0; c < 3; c++) out[oi + c] = out[oi + c] * product[si + c] / 255;
  }
  return (0, import_sharp2.default)(out, { raw: { width: W3, height: H3, channels: 3 } }).jpeg({ quality: output.quality || STYLE.jpegQuality, mozjpeg: true, ...output.chroma444 ? { chromaSubsampling: "4:4:4" } : {} }).toBuffer();
}

// ../parfumdeclaration-web/apps/api/src/lib/notes-card.ts
var import_node_path2 = __toESM(require("node:path"));
var import_sharp3 = __toESM(require("sharp"));
var ASSETS = import_node_path2.default.resolve(__dirname, "./assets");
var FONT = {
  serif: { file: import_node_path2.default.join(ASSETS, "fonts/CormorantGaramond-SemiBold.ttf"), family: "Cormorant Garamond SemiBold" },
  medium: { file: import_node_path2.default.join(ASSETS, "fonts/Manrope-Medium.ttf"), family: "Manrope Medium" },
  bold: { file: import_node_path2.default.join(ASSETS, "fonts/Manrope-Bold.ttf"), family: "Manrope Bold" },
  extra: { file: import_node_path2.default.join(ASSETS, "fonts/Manrope-ExtraBold.ttf"), family: "Manrope ExtraBold" }
};
var THEMES = {
  magicstick: { logo: "magicstick-logo.png", bg1: "#f6f2fb", bg2: "#e2d6f0", ink: "#2a1747", soft: "#6c5a86", acc: "#7b4fc4", acc2: "#b99ae6", blob: "rgba(160,120,220,0.22)", panel: "rgba(255,255,255,0.58)" },
  // Яндекс Маркет (Parfumerius): лаванда с золотом, как его финальные фото
  parfumerius: { logo: "parfumerius-logo.png", bg1: "#f7f2fb", bg2: "#e6daf1", ink: "#2f1a52", soft: "#6f5a8c", acc: "#b8913f", acc2: "#dcbf7a", blob: "rgba(170,130,225,0.20)", panel: "rgba(255,255,255,0.6)" },
  aura: { logo: "aura-logo.png", bg1: "#fbf6ef", bg2: "#efe2cf", ink: "#3a2a1c", soft: "#7a6450", acc: "#b0843a", acc2: "#d9b877", blob: "rgba(214,186,140,0.28)", panel: "rgba(255,255,255,0.6)" }
};
var W = 1200;
var H = 1600;
var PER_ROW = 7;
var ICON = 112;
var ROW_H = ICON + 74;
var ACCORDS_H = 250;
function esc(text2) {
  return String(text2 ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
async function text(markup, font, size, opts = {}) {
  const { data, info } = await (0, import_sharp3.default)({
    text: {
      text: markup,
      font: `${font.family} ${size}`,
      fontfile: font.file,
      width: opts.width,
      align: opts.align ?? "centre",
      rgba: true,
      dpi: 72,
      wrap: "word",
      spacing: opts.spacing
    }
  }).png().toBuffer({ resolveWithObject: true });
  return { input: data, width: info.width, height: info.height };
}
function sparkle(x, y, r, color, opacity) {
  const k = r * 0.18;
  return `<path transform="translate(${x} ${y})" fill="${color}" fill-opacity="${opacity}" d="M0 ${-r} C${k} ${-k} ${k} ${-k} ${r} 0 C${k} ${k} ${k} ${k} 0 ${r} C${-k} ${k} ${-k} ${k} ${-r} 0 C${-k} ${-k} ${-k} ${-k} 0 ${-r}Z"/>`;
}
async function fetchIcon(url, size) {
  try {
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0", Referer: "https://www.fragrantica.ru/" }, signal: AbortSignal.timeout(2e4) });
    if (!res.ok) return null;
    const raw = Buffer.from(await res.arrayBuffer());
    const mask = Buffer.from(`<svg width="${size}" height="${size}"><circle cx="${size / 2}" cy="${size / 2}" r="${size / 2}" fill="#fff"/></svg>`);
    return await (0, import_sharp3.default)(raw, { failOn: "none" }).resize(size, size, { fit: "cover" }).composite([{ input: mask, blend: "dest-in" }]).png().toBuffer();
  } catch {
    return null;
  }
}
function cardTiers(notes) {
  const tiers = [
    { label: "\u0412\u0435\u0440\u0445\u043D\u0438\u0435 \u043D\u043E\u0442\u044B", notes: notes.top ?? [] },
    { label: "\u041D\u043E\u0442\u044B \u0441\u0435\u0440\u0434\u0446\u0430", notes: notes.middle ?? [] },
    { label: "\u0411\u0430\u0437\u043E\u0432\u044B\u0435 \u043D\u043E\u0442\u044B", notes: notes.base ?? [] }
  ].filter((t) => t.notes.length);
  if (!tiers.length && notes.flat?.length) tiers.push({ label: "\u041D\u043E\u0442\u044B", notes: notes.flat });
  const max = tiers.length === 1 ? PER_ROW * 2 : PER_ROW;
  return tiers.map((t) => ({ ...t, notes: t.notes.slice(0, max) }));
}
async function renderNotesCard(perfume, style = "magicstick") {
  const t = THEMES[style] ?? THEMES.magicstick;
  const tiers = cardTiers(perfume.notes ?? {});
  const accords = (perfume.accords ?? []).filter((a) => a.name).slice(0, 5);
  const logo = await (0, import_sharp3.default)(import_node_path2.default.join(ASSETS, t.logo)).resize({ width: 360, height: 230, fit: "inside" }).linear(1.04, 0).png().toBuffer({ resolveWithObject: true });
  const top = 36 + logo.info.height + 10 + 230;
  const bottom = 1570;
  const gap = 22;
  const panelHeights = tiers.map((tier) => 70 + Math.ceil(tier.notes.length / PER_ROW) * ROW_H);
  const stackH = panelHeights.reduce((a, b) => a + b, 0) + Math.max(0, tiers.length - 1) * gap;
  const contentH = stackH + (accords.length ? (tiers.length ? 40 : 0) + ACCORDS_H : 0);
  const y0 = top + Math.max(0, Math.floor((bottom - top - contentH) / 2));
  const panelX = 60;
  const panelW = W - 120;
  const panelY = panelHeights.map((_, i) => y0 + panelHeights.slice(0, i).reduce((a, b) => a + b, 0) + i * gap);
  const panels = tiers.map((_, i) => `<rect x="${panelX}" y="${panelY[i]}" width="${panelW}" height="${panelHeights[i]}" rx="30" fill="${t.panel}" stroke="${t.acc2}" stroke-opacity="0.45" stroke-width="2"/>`).join("");
  const accordY = y0 + stackH + (tiers.length ? 40 : 0);
  const bars = accords.map((a, i) => {
    const y2 = accordY + 48 + i * 40;
    const share = Math.max(18, Math.min(100, Number(a.share) || 60));
    const trackX = 380;
    const trackW = W - trackX - 90;
    return `<rect x="${trackX}" y="${y2}" width="${trackW}" height="20" rx="10" fill="${t.acc2}" fill-opacity="0.25"/><rect x="${trackX}" y="${y2}" width="${Math.round(trackW * share / 100)}" height="20" rx="10" fill="url(#bar)"/>`;
  }).join("");
  const background = Buffer.from(`<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${t.bg1}"/><stop offset="1" stop-color="${t.bg2}"/></linearGradient>
      <radialGradient id="blob"><stop offset="0" stop-color="${t.blob}"/><stop offset="1" stop-color="${t.blob}" stop-opacity="0"/></radialGradient>
      <linearGradient id="bar" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="${t.acc}"/><stop offset="1" stop-color="${t.acc2}"/></linearGradient>
    </defs>
    <rect width="${W}" height="${H}" fill="url(#bg)"/>
    <circle cx="160" cy="260" r="360" fill="url(#blob)"/>
    <circle cx="1080" cy="900" r="420" fill="url(#blob)"/>
    <circle cx="300" cy="1450" r="320" fill="url(#blob)"/>
    ${sparkle(110, 120, 16, t.acc, 0.45)}${sparkle(1090, 200, 12, t.acc, 0.4)}${sparkle(1120, 1240, 14, t.acc2, 0.5)}${sparkle(70, 820, 10, t.acc2, 0.5)}
    ${panels}
    ${bars}
  </svg>`);
  const layers = [];
  const centred = (img, y2) => layers.push({ input: img.input, left: Math.round((W - img.width) / 2), top: Math.round(y2) });
  layers.push({ input: logo.data, left: Math.round((W - logo.info.width) / 2), top: 36, blend: "multiply" });
  let y = 36 + logo.info.height + 10;
  const kicker = await text(`<span foreground="${t.acc}" letter_spacing="6000">\u0413\u0418\u0414 \u041F\u041E \u0410\u0420\u041E\u041C\u0410\u0422\u0423</span>`, FONT.extra, 17);
  centred(kicker, y);
  y += kicker.height + 6;
  const title = await text(`<span foreground="${t.ink}">\u041F\u0438\u0440\u0430\u043C\u0438\u0434\u0430 \u0430\u0440\u043E\u043C\u0430\u0442\u0430</span>`, FONT.serif, 84);
  centred(title, y);
  y += title.height;
  const subtitle = await text(`<span foreground="${t.soft}">${esc(`${perfume.brand} \xB7 ${perfume.name}`)}</span>`, FONT.medium, 28, { width: W - 160 });
  centred(subtitle, Math.min(y + 4, top - subtitle.height - 8));
  const icon = ICON;
  for (let i = 0; i < tiers.length; i += 1) {
    const tier = tiers[i];
    const py = panelY[i];
    const label = await text(`<span foreground="${t.acc}" letter_spacing="4000">${esc(tier.label.toUpperCase())}</span>`, FONT.extra, 18);
    centred(label, py + 22);
    const images = await Promise.all(tier.notes.map((n) => n.icon ? fetchIcon(n.icon, icon) : Promise.resolve(null)));
    for (let k = 0; k < tier.notes.length; k += 1) {
      const row = Math.floor(k / PER_ROW);
      const inRow = Math.min(PER_ROW, tier.notes.length - row * PER_ROW);
      const slot = Math.min(150, Math.floor((panelW - 40) / PER_ROW));
      const cx = Math.round((W - slot * inRow) / 2) + k % PER_ROW * slot + slot / 2;
      const iconY = py + 70 + row * ROW_H;
      const ring = Buffer.from(`<svg width="${icon + 8}" height="${icon + 8}"><circle cx="${(icon + 8) / 2}" cy="${(icon + 8) / 2}" r="${icon / 2 + 2}" fill="#ffffff" stroke="${t.acc2}" stroke-width="2"/></svg>`);
      layers.push({ input: ring, left: Math.round(cx - (icon + 8) / 2), top: iconY - 4 });
      if (images[k]) {
        layers.push({ input: images[k], left: Math.round(cx - icon / 2), top: iconY });
      } else {
        const letter = await text(`<span foreground="${t.acc}">${esc(tier.notes[k].name.charAt(0).toUpperCase())}</span>`, FONT.serif, 64);
        const disc = Buffer.from(`<svg width="${icon}" height="${icon}"><circle cx="${icon / 2}" cy="${icon / 2}" r="${icon / 2}" fill="${t.acc2}" fill-opacity="0.22"/></svg>`);
        layers.push({ input: disc, left: Math.round(cx - icon / 2), top: iconY });
        layers.push({ input: letter.input, left: Math.round(cx - letter.width / 2), top: Math.round(iconY + (icon - letter.height) / 2) });
      }
      const name = tier.notes[k].name.length > 26 ? `${tier.notes[k].name.slice(0, 25)}\u2026` : tier.notes[k].name;
      const caption = await text(`<span foreground="${t.ink}">${esc(name)}</span>`, FONT.bold, 17, { width: slot - 8 });
      layers.push({ input: caption.input, left: Math.round(cx - caption.width / 2), top: iconY + icon + 10 });
    }
  }
  if (accords.length) {
    const head = await text(`<span foreground="${t.acc}" letter_spacing="4000">\u041E\u0421\u041D\u041E\u0412\u041D\u042B\u0415 \u0410\u041A\u041A\u041E\u0420\u0414\u042B</span>`, FONT.extra, 18);
    centred(head, accordY);
    for (let i = 0; i < accords.length; i += 1) {
      const name = accords[i].name.charAt(0).toUpperCase() + accords[i].name.slice(1);
      const label = await text(`<span foreground="${t.ink}">${esc(name)}</span>`, FONT.bold, 22, { width: 270, align: "right" });
      layers.push({ input: label.input, left: 350 - label.width, top: accordY + 48 + i * 40 + 10 - Math.round(label.height / 2) });
    }
  }
  return (0, import_sharp3.default)(background).composite(layers).jpeg({ quality: 95, mozjpeg: true, chromaSubsampling: "4:4:4" }).toBuffer();
}
var CARD_FONT = FONT;
var renderTextBlock = text;
var cardTheme = (style) => THEMES[style] ?? THEMES.magicstick;
async function cardLogo(style) {
  return (0, import_sharp3.default)(import_node_path2.default.join(ASSETS, cardTheme(style).logo)).resize({ width: 360, height: 230, fit: "inside" }).linear(1.04, 0).png().toBuffer({ resolveWithObject: true });
}
function cardBackgroundSvg(style, w, h, extra = "") {
  const t = cardTheme(style);
  return `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${t.bg1}"/><stop offset="1" stop-color="${t.bg2}"/></linearGradient>
      <radialGradient id="blob"><stop offset="0" stop-color="${t.blob}"/><stop offset="1" stop-color="${t.blob}" stop-opacity="0"/></radialGradient>
    </defs>
    <rect width="${w}" height="${h}" fill="url(#bg)"/>
    <circle cx="160" cy="260" r="360" fill="url(#blob)"/>
    <circle cx="${w - 120}" cy="${Math.round(h * 0.56)}" r="420" fill="url(#blob)"/>
    <circle cx="300" cy="${h - 150}" r="320" fill="url(#blob)"/>
    ${sparkle(110, 120, 16, t.acc, 0.45)}${sparkle(w - 110, 200, 12, t.acc, 0.4)}${sparkle(w - 80, h - 360, 14, t.acc2, 0.5)}
    ${extra}
  </svg>`;
}

// ../parfumdeclaration-web/apps/api/src/lib/perfume-extra.ts
var import_sharp4 = __toESM(require("sharp"));
var W2 = 1200;
var H2 = 1600;
function whiteProductBox(data, w, h, channels) {
  let x0 = w, y0 = h, x1 = -1, y1 = -1;
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const i = (y * w + x) * channels;
    if (255 - Math.min(data[i], data[i + 1], data[i + 2]) > 14) {
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  return x1 < 0 ? null : { left: x0, top: y0, width: x1 - x0 + 1, height: y1 - y0 + 1 };
}
async function renderCloseup(source) {
  const { data, info } = await (0, import_sharp4.default)(source, { failOn: "none" }).rotate().removeAlpha().raw().toBuffer({ resolveWithObject: true });
  if (!isWhiteBackground(data, info.width, info.height, info.channels)) return null;
  const box = whiteProductBox(data, info.width, info.height, info.channels);
  if (!box || box.height < 300) return null;
  let ch = Math.round(box.height * 0.62);
  let cw = Math.round(ch * 3 / 4);
  if (cw < box.width * 0.9) {
    cw = Math.round(box.width * 0.9);
    ch = Math.round(cw * 4 / 3);
  }
  const left = Math.round(box.left + box.width / 2 - cw / 2);
  const top = Math.round(box.top - box.height * 0.04);
  const pad = Math.max(cw, ch);
  const padded = await (0, import_sharp4.default)(data, { raw: { width: info.width, height: info.height, channels: info.channels } }).extend({ top: pad, bottom: pad, left: pad, right: pad, background: { r: 255, g: 255, b: 255 } }).raw().toBuffer({ resolveWithObject: true });
  const crop = await (0, import_sharp4.default)(padded.data, { raw: { width: padded.info.width, height: padded.info.height, channels: 3 } }).extract({ left: left + pad, top: top + pad, width: cw, height: ch }).raw().toBuffer({ resolveWithObject: true });
  let img = (0, import_sharp4.default)(crop.data, { raw: { width: crop.info.width, height: crop.info.height, channels: 3 } });
  if (ch < H2 && cw * ch <= 1e6) {
    const up = await aiUpscale(crop.data, crop.info.width, crop.info.height);
    img = (0, import_sharp4.default)(up.data, { raw: { width: up.width, height: up.height, channels: 3 } });
  }
  return img.resize(W2, H2, { kernel: "lanczos3" }).sharpen({ sigma: 0.6 }).jpeg({ quality: 95, mozjpeg: true, chromaSubsampling: "4:4:4" }).toBuffer();
}
var GENDER = { male: "\u041C\u0443\u0436\u0441\u043A\u043E\u0439", female: "\u0416\u0435\u043D\u0441\u043A\u0438\u0439", unisex: "\u0423\u043D\u0438\u0441\u0435\u043A\u0441" };
async function renderSpecsCard(perfume, main, style) {
  const t = cardTheme(style);
  const rows = [
    ["\u0411\u0440\u0435\u043D\u0434", perfume.brand],
    ["\u0410\u0440\u043E\u043C\u0430\u0442", perfume.name],
    ["\u0414\u043B\u044F \u043A\u043E\u0433\u043E", GENDER[perfume.gender ?? ""] ?? ""],
    ["\u0413\u043E\u0434 \u0432\u044B\u043F\u0443\u0441\u043A\u0430", perfume.year ? String(perfume.year) : ""],
    ["\u0421\u0435\u043C\u0435\u0439\u0441\u0442\u0432\u043E", (perfume.accords ?? []).slice(0, 3).map((a) => a.name).filter(Boolean).join(", ")],
    ["\u041F\u0430\u0440\u0444\u044E\u043C\u0435\u0440", (perfume.perfumers ?? []).slice(0, 2).join(", ")],
    ["\u0421\u0442\u0440\u0430\u043D\u0430 \u0431\u0440\u0435\u043D\u0434\u0430", perfume.country ?? ""]
  ].filter(([, v]) => String(v || "").trim());
  const logo = await cardLogo(style);
  const layers = [];
  layers.push({ input: logo.data, left: Math.round((W2 - logo.info.width) / 2), top: 36, blend: "multiply" });
  let y = 36 + logo.info.height + 10;
  const kicker = await renderTextBlock(`<span foreground="${t.acc}" letter_spacing="6000">\u0425\u0410\u0420\u0410\u041A\u0422\u0415\u0420\u0418\u0421\u0422\u0418\u041A\u0418</span>`, CARD_FONT.extra, 17);
  layers.push({ input: kicker.input, left: Math.round((W2 - kicker.width) / 2), top: y });
  y += kicker.height + 6;
  const title = await renderTextBlock(`<span foreground="${t.ink}">\u041E \u0430\u0440\u043E\u043C\u0430\u0442\u0435</span>`, CARD_FONT.serif, 84);
  layers.push({ input: title.input, left: Math.round((W2 - title.width) / 2), top: y });
  y += title.height + 30;
  const header = y;
  const photoW = 520;
  const photoH = Math.round(photoW * 4 / 3);
  const m = await (0, import_sharp4.default)(main).metadata();
  const mh = m.height ?? 2e3;
  const mw = m.width ?? 1500;
  const cropH = Math.round(mh * 0.74);
  const cropW = Math.min(mw, Math.round(cropH * 3 / 4));
  const photo = await (0, import_sharp4.default)(main).extract({ left: Math.round((mw - cropW) / 2), top: Math.round(mh * 0.13), width: cropW, height: cropH }).resize(photoW, photoH, { fit: "cover", kernel: "lanczos3" }).png().toBuffer();
  const mask = Buffer.from(`<svg width="${photoW}" height="${photoH}"><rect width="${photoW}" height="${photoH}" rx="34" fill="#fff"/></svg>`);
  const rounded = await (0, import_sharp4.default)(photo).composite([{ input: mask, blend: "dest-in" }]).png().toBuffer();
  const photoX = 60;
  const panelX = photoX + photoW + 40;
  const panelW = W2 - panelX - 60;
  const rowBlocks = [];
  for (const [label, value] of rows) {
    rowBlocks.push({
      label: await renderTextBlock(`<span foreground="${t.acc}" letter_spacing="2500">${esc2(label.toUpperCase())}</span>`, CARD_FONT.extra, 16, { width: panelW - 60, align: "left" }),
      value: await renderTextBlock(`<span foreground="${t.ink}">${esc2(value)}</span>`, CARD_FONT.bold, 34, { width: panelW - 60, align: "left" })
    });
  }
  const rowsH = rowBlocks.reduce((sum, r) => sum + r.label.height + 6 + r.value.height + 30, 20);
  const panelH = Math.max(photoH, rowsH + 30);
  const photoY = header + Math.max(20, Math.round((H2 - 60 - header - panelH) * 0.38));
  layers.push({ input: rounded, left: photoX, top: photoY + Math.round((panelH - photoH) / 2) });
  let ry = photoY + Math.round((panelH - rowsH) / 2) + 10;
  for (const r of rowBlocks) {
    layers.push({ input: r.label.input, left: panelX + 30, top: ry });
    ry += r.label.height + 6;
    layers.push({ input: r.value.input, left: panelX + 30, top: ry });
    ry += r.value.height + 30;
  }
  const extraSvg = `<rect x="${panelX}" y="${photoY}" width="${panelW}" height="${panelH}" rx="30" fill="${t.panel}" stroke="${t.acc2}" stroke-opacity="0.45" stroke-width="2"/><rect x="${photoX - 6}" y="${photoY + Math.round((panelH - photoH) / 2) - 6}" width="${photoW + 12}" height="${photoH + 12}" rx="38" fill="none" stroke="${t.acc2}" stroke-opacity="0.6" stroke-width="2"/>`;
  const background = Buffer.from(cardBackgroundSvg(style, W2, H2, extraSvg));
  return (0, import_sharp4.default)(background).composite(layers).jpeg({ quality: 95, mozjpeg: true, chromaSubsampling: "4:4:4" }).toBuffer();
}
function esc2(text2) {
  return String(text2 ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
var TIER_TEXT = {
  top: { title: "\u0412\u0435\u0440\u0445\u043D\u0438\u0435 \u043D\u043E\u0442\u044B", lead: "\u041F\u0435\u0440\u0432\u043E\u0435 \u0432\u043F\u0435\u0447\u0430\u0442\u043B\u0435\u043D\u0438\u0435: \u0437\u0432\u0443\u0447\u0430\u0442 \u0441\u0440\u0430\u0437\u0443 \u043F\u043E\u0441\u043B\u0435 \u043D\u0430\u043D\u0435\u0441\u0435\u043D\u0438\u044F" },
  middle: { title: "\u041D\u043E\u0442\u044B \u0441\u0435\u0440\u0434\u0446\u0430", lead: "\u0425\u0430\u0440\u0430\u043A\u0442\u0435\u0440 \u0430\u0440\u043E\u043C\u0430\u0442\u0430: \u0440\u0430\u0441\u043A\u0440\u044B\u0432\u0430\u044E\u0442\u0441\u044F, \u043A\u043E\u0433\u0434\u0430 \u0432\u0435\u0440\u0445\u043D\u0438\u0435 \u043D\u043E\u0442\u044B \u0441\u0442\u0438\u0445\u0430\u044E\u0442" },
  base: { title: "\u0411\u0430\u0437\u043E\u0432\u044B\u0435 \u043D\u043E\u0442\u044B", lead: "\u0428\u043B\u0435\u0439\u0444: \u0434\u0435\u0440\u0436\u0430\u0442\u0441\u044F \u043D\u0430 \u043A\u043E\u0436\u0435 \u0434\u043E\u043B\u044C\u0448\u0435 \u0432\u0441\u0435\u0433\u043E" },
  flat: { title: "\u041D\u043E\u0442\u044B \u0430\u0440\u043E\u043C\u0430\u0442\u0430", lead: "\u0410\u0440\u043E\u043C\u0430\u0442 \u0437\u0432\u0443\u0447\u0438\u0442 \u0446\u0435\u043B\u044C\u043D\u043E, \u0431\u0435\u0437 \u0434\u0435\u043B\u0435\u043D\u0438\u044F \u043D\u0430 \u044F\u0440\u0443\u0441\u044B" }
};
async function fetchRoundIcon(url, size) {
  try {
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0", Referer: "https://www.fragrantica.ru/" }, signal: AbortSignal.timeout(2e4) });
    if (!res.ok) return null;
    const raw = Buffer.from(await res.arrayBuffer());
    const mask = Buffer.from(`<svg width="${size}" height="${size}"><circle cx="${size / 2}" cy="${size / 2}" r="${size / 2}" fill="#fff"/></svg>`);
    return await (0, import_sharp4.default)(raw, { failOn: "none" }).resize(size, size, { fit: "cover", kernel: "lanczos3" }).composite([{ input: mask, blend: "dest-in" }]).png().toBuffer();
  } catch {
    return null;
  }
}
function tierKeys(notes) {
  const keys = ["top", "middle", "base"].filter((k) => (notes[k] ?? []).length);
  return keys.length ? [...keys] : (notes.flat ?? []).length ? ["flat"] : [];
}
async function cardHeader(style, kickerText, titleText, subtitleText, layers) {
  const t = cardTheme(style);
  const logo = await cardLogo(style);
  layers.push({ input: logo.data, left: Math.round((W2 - logo.info.width) / 2), top: 36, blend: "multiply" });
  let y = 36 + logo.info.height + 10;
  const kicker = await renderTextBlock(`<span foreground="${t.acc}" letter_spacing="6000">${esc2(kickerText)}</span>`, CARD_FONT.extra, 17);
  layers.push({ input: kicker.input, left: Math.round((W2 - kicker.width) / 2), top: y });
  y += kicker.height + 6;
  const title = await renderTextBlock(`<span foreground="${t.ink}">${esc2(titleText)}</span>`, CARD_FONT.serif, 84);
  layers.push({ input: title.input, left: Math.round((W2 - title.width) / 2), top: y });
  y += title.height + 4;
  const sub = await renderTextBlock(`<span foreground="${t.soft}">${esc2(subtitleText)}</span>`, CARD_FONT.medium, 28, { width: W2 - 160 });
  layers.push({ input: sub.input, left: Math.round((W2 - sub.width) / 2), top: y });
  return y + sub.height;
}
async function renderTierCard(perfume, tier, style) {
  const t = cardTheme(style);
  const notes = (perfume.notes[tier] ?? []).slice(0, 9);
  const text2 = TIER_TEXT[tier];
  const layers = [];
  const headerBottom = await cardHeader(style, "\u0413\u0418\u0414 \u041F\u041E \u0410\u0420\u041E\u041C\u0410\u0422\u0423", text2.title, `${perfume.brand} \xB7 ${perfume.name}`, layers);
  const lead = await renderTextBlock(`<span foreground="${t.ink}">${esc2(text2.lead)}</span>`, CARD_FONT.bold, 30, { width: W2 - 220 });
  const perRow = notes.length <= 4 ? 2 : 3;
  const icon = notes.length <= 2 ? 300 : notes.length <= 4 ? 260 : 220;
  const rowH = icon + 110;
  const rows = Math.ceil(notes.length / perRow);
  const panelX = 70;
  const panelW = W2 - 140;
  const panelH = 70 + lead.height + 40 + rows * rowH + 20;
  const panelY = headerBottom + Math.max(30, Math.round((1560 - headerBottom - panelH) / 2));
  layers.push({ input: lead.input, left: Math.round((W2 - lead.width) / 2), top: panelY + 50 });
  const gridY = panelY + 50 + lead.height + 40;
  const images = await Promise.all(notes.map((n) => n.icon ? fetchRoundIcon(n.icon, icon) : Promise.resolve(null)));
  for (let k = 0; k < notes.length; k += 1) {
    const row = Math.floor(k / perRow);
    const inRow = Math.min(perRow, notes.length - row * perRow);
    const slot = Math.floor((panelW - 60) / perRow);
    const cx = Math.round((W2 - slot * inRow) / 2) + k % perRow * slot + slot / 2;
    const iy = gridY + row * rowH;
    const ring = Buffer.from(`<svg width="${icon + 12}" height="${icon + 12}"><circle cx="${(icon + 12) / 2}" cy="${(icon + 12) / 2}" r="${icon / 2 + 4}" fill="#ffffff" stroke="${t.acc2}" stroke-width="3"/></svg>`);
    layers.push({ input: ring, left: Math.round(cx - (icon + 12) / 2), top: iy - 6 });
    if (images[k]) {
      layers.push({ input: images[k], left: Math.round(cx - icon / 2), top: iy });
    } else {
      const disc = Buffer.from(`<svg width="${icon}" height="${icon}"><circle cx="${icon / 2}" cy="${icon / 2}" r="${icon / 2}" fill="${t.acc2}" fill-opacity="0.22"/></svg>`);
      const letter = await renderTextBlock(`<span foreground="${t.acc}">${esc2(notes[k].name.charAt(0).toUpperCase())}</span>`, CARD_FONT.serif, Math.round(icon * 0.55));
      layers.push({ input: disc, left: Math.round(cx - icon / 2), top: iy });
      layers.push({ input: letter.input, left: Math.round(cx - letter.width / 2), top: Math.round(iy + (icon - letter.height) / 2) });
    }
    const caption = await renderTextBlock(`<span foreground="${t.ink}">${esc2(notes[k].name)}</span>`, CARD_FONT.bold, 30, { width: slot - 20 });
    layers.push({ input: caption.input, left: Math.round(cx - caption.width / 2), top: iy + icon + 18 });
  }
  const panel = `<rect x="${panelX}" y="${panelY}" width="${panelW}" height="${panelH}" rx="34" fill="${t.panel}" stroke="${t.acc2}" stroke-opacity="0.45" stroke-width="2"/>`;
  return (0, import_sharp4.default)(Buffer.from(cardBackgroundSvg(style, W2, H2, panel))).composite(layers).jpeg({ quality: 95, mozjpeg: true, chromaSubsampling: "4:4:4" }).toBuffer();
}
async function renderAccordsCard(perfume, style) {
  const t = cardTheme(style);
  const accords = (perfume.accords ?? []).filter((a) => a.name).slice(0, 8);
  if (accords.length < 2) return null;
  const layers = [];
  const headerBottom = await cardHeader(style, "\u0413\u0418\u0414 \u041F\u041E \u0410\u0420\u041E\u041C\u0410\u0422\u0423", "\u0410\u043A\u043A\u043E\u0440\u0434\u044B \u0430\u0440\u043E\u043C\u0430\u0442\u0430", `${perfume.brand} \xB7 ${perfume.name}`, layers);
  const lead = await renderTextBlock(`<span foreground="${t.ink}">\u0418\u0437 \u0447\u0435\u0433\u043E \u0441\u043A\u043B\u0430\u0434\u044B\u0432\u0430\u0435\u0442\u0441\u044F \u0437\u0432\u0443\u0447\u0430\u043D\u0438\u0435 \u2014 \u0447\u0435\u043C \u0434\u043B\u0438\u043D\u043D\u0435\u0435 \u043F\u043E\u043B\u043E\u0441\u0430, \u0442\u0435\u043C \u044F\u0440\u0447\u0435 \u0430\u043A\u043A\u043E\u0440\u0434</span>`, CARD_FONT.bold, 28, { width: W2 - 240 });
  const rowH = Math.max(104, Math.min(170, Math.floor((1500 - headerBottom - lead.height - 170) / accords.length)));
  const barH = Math.round(rowH * 0.7);
  const panelX = 70;
  const panelW = W2 - 140;
  const panelH = 60 + lead.height + 50 + accords.length * rowH + 30;
  const panelY = headerBottom + Math.max(30, Math.round((1560 - headerBottom - panelH) / 2));
  layers.push({ input: lead.input, left: Math.round((W2 - lead.width) / 2), top: panelY + 46 });
  const top = panelY + 46 + lead.height + 50;
  const max = Math.max(...accords.map((a) => Number(a.share) || 0), 1);
  const trackX = panelX + 50;
  const trackW = panelW - 100;
  let bars = "";
  for (let i = 0; i < accords.length; i += 1) {
    const a = accords[i];
    const y = top + i * rowH;
    const share = Number(a.share) > 0 ? Number(a.share) / max * 100 : 100 - i * 9;
    const width = Math.max(220, Math.round(trackW * share / 100));
    const color = /^#[0-9a-f]{3,8}$|^rgb/i.test(String(a.background || "")) ? String(a.background) : t.acc;
    bars += `<rect x="${trackX}" y="${y}" width="${trackW}" height="${barH}" rx="${barH / 2}" fill="${t.acc2}" fill-opacity="0.18"/><rect x="${trackX}" y="${y}" width="${width}" height="${barH}" rx="${barH / 2}" fill="${color}"/>`;
    const name = a.name.charAt(0).toUpperCase() + a.name.slice(1);
    const light = luminance(color) > 0.6;
    const label = await renderTextBlock(`<span foreground="${light ? t.ink : "#ffffff"}">${esc2(name)}</span>`, CARD_FONT.extra, Math.round(barH * 0.42), { width: Math.max(200, width - 60), align: "left" });
    layers.push({ input: label.input, left: trackX + 34, top: Math.round(y + barH / 2 - label.height / 2) });
  }
  const panel = `<rect x="${panelX}" y="${panelY}" width="${panelW}" height="${panelH}" rx="34" fill="${t.panel}" stroke="${t.acc2}" stroke-opacity="0.45" stroke-width="2"/>${bars}`;
  return (0, import_sharp4.default)(Buffer.from(cardBackgroundSvg(style, W2, H2, panel))).composite(layers).jpeg({ quality: 95, mozjpeg: true, chromaSubsampling: "4:4:4" }).toBuffer();
}
function luminance(color) {
  let r = 0, g = 0, b = 0;
  const hex = /^#([0-9a-f]{3}|[0-9a-f]{6})/i.exec(color);
  const rgb = /rgba?\((\d+)\D+(\d+)\D+(\d+)/i.exec(color);
  if (hex) {
    const h = hex[1].length === 3 ? hex[1].split("").map((c) => c + c).join("") : hex[1];
    r = parseInt(h.slice(0, 2), 16);
    g = parseInt(h.slice(2, 4), 16);
    b = parseInt(h.slice(4, 6), 16);
  } else if (rgb) {
    r = Number(rgb[1]);
    g = Number(rgb[2]);
    b = Number(rgb[3]);
  } else return 0;
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255;
}

// lib/perfume-render/entry.ts
async function renderPerfumeCard({ source, styles, perfume, extras = true }) {
  const warnings = [];
  let main = await premiumBackground(source, { width: 1500, height: 2e3, quality: 95, chroma444: true }).catch((e) => {
    warnings.push(`\u041F\u0440\u0435\u043C\u0438\u0443\u043C \u0444\u043E\u043D: ${e?.message || e}`);
    return null;
  });
  if (!main) {
    warnings.push("\u0424\u043E\u0442\u043E \u043D\u0435 \u043D\u0430 \u0431\u0435\u043B\u043E\u043C \u0444\u043E\u043D\u0435 \u2014 \u043F\u0440\u0435\u043C\u0438\u0443\u043C \u0444\u043E\u043D \u043D\u0435 \u043F\u0440\u0438\u043C\u0435\u043D\u0451\u043D");
    main = await enhanceSmallPhoto(source).catch(() => null);
  }
  if (!main) main = await (0, import_sharp5.default)(source, { failOn: "none" }).rotate().jpeg({ quality: 95, mozjpeg: true, chromaSubsampling: "4:4:4" }).toBuffer();
  const notesByStyle = {};
  for (const style of styles) notesByStyle[style] = await renderNotesCard(perfume, style);
  const out = { main, notesByStyle, closeup: null, specsByStyle: {}, tiersByStyle: {}, accordsByStyle: {}, warnings };
  if (!extras) return out;
  out.closeup = await renderCloseup(source).catch((e) => {
    warnings.push(`\u041A\u0440\u0443\u043F\u043D\u044B\u0439 \u043F\u043B\u0430\u043D: ${e?.message || e}`);
    return null;
  });
  const tiers = tierKeys(perfume.notes ?? {});
  for (const style of styles) {
    const specs = await renderSpecsCard(perfume, main, style).catch((e) => {
      warnings.push(`\u0425\u0430\u0440\u0430\u043A\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043A\u0438: ${e?.message || e}`);
      return null;
    });
    if (specs) out.specsByStyle[style] = specs;
    out.tiersByStyle[style] = [];
    for (const tier of tiers) {
      const card = await renderTierCard(perfume, tier, style).catch((e) => {
        warnings.push(`\u041D\u043E\u0442\u044B (${tier}): ${e?.message || e}`);
        return null;
      });
      if (card) out.tiersByStyle[style].push({ tier, image: card });
    }
    const accords = await renderAccordsCard(perfume, style).catch((e) => {
      warnings.push(`\u0410\u043A\u043A\u043E\u0440\u0434\u044B: ${e?.message || e}`);
      return null;
    });
    if (accords) out.accordsByStyle[style] = accords;
  }
  return out;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  renderPerfumeCard
});
